### ISSUE TITLE
Chunking for large content

### ISSUE THREAD

**Issue by lbovet** [BEagle1984/silverback#106] opened 2020-08-27 12:11 UTC
Currently, chunking assumes that the whole message fits in memory. When dealing with large content (hundreds of MB), this model is limited.
This issue starts the discussion how support could be provided for dealing with large chunked messages in a streamed fashion.

**Comment by BEagle1984** [comment] 2020-08-27 13:02
It would theoretically be possible to provide the binary content as a stream. The most natural API I guess it would be to have a version of the [`BinaryFileMessage`](https://github.com/BEagle1984/silverback/blob/master/src/Silverback.Integration/Messaging/Messages/BinaryFileMessage.cs) that declares the content as a `Stream` instead of a simple byte array.
Producing via a stream would be trivial: just read the stream till the desired chunk size, produce the message, repeat until the end of stream.
Consuming on the other hand might be a bit more tricky: I imagine that a `BinaryStreamMessage` would be published to the internal bus as soon as the first chunk in being received and then the further chunks are just being pushed to the open stream. (It sounds simple but for sure it isn't so trivial.)

(How to properly implement the stream, in an optimal way and of course avoiding to have the whole file being held in memory at any given time....well, that's an implementation detail.)

**Comment by lbovet** [comment] 2020-08-27 13:51
Yes, consuming is the tricky part. In any case, the existing support for chunking is not really helpful for a streaming solution.

For consuming, the challenge is to transform the flow of messages pushed by the poll loop into a flow of pulled messages (IEnumerable in the general case, Stream in the binary chunk case).

And we need back pressure if we don't read the Stream as fast as the messages are produced. If everything runs sync, we just introduce a blocking queue in the middle. I have not yet understood the threading model between the Kafka Consumer and the "internal bus". What happens if my business consumer blocks the thread in OnMessage(...)? Does it also block the poll loop of the consumer? Is it problem?

**Comment by lbovet** [comment] 2020-08-27 15:54
Here is what I envision:

1. A new module `Silverback.Integration.Sequence` providing dataset and streamed chunking. The goal is to have a minimum impact to the rest of the codebase.
1. Providing a message type `Sequence<T>`
1. Support enabled with something like `.AddSequenceSupport<T>()` to the configuration.
1. This creates a new subscriber for T, a `SequenceItemSubscriber<T>`
1. Upon receiving the first item of a sequence, it will publish a sequence message backed with a `BlockingCollection` of size 1 and will write the sequence items into this blocking collection. The sequence message is of type `Sequence<T>` which contains the sequence id and an `IEnumerable<T>`
1. Consumers can subscribe to `Sequence<T>` as they would subscribe to other message types.
1. When T is byte[], then an additional internal subscriber is created. It listens to `Sequence<byte[]>` and publishes `BinarySequence` which contains the sequence id and a `Stream` backed by the blocking collection.

I have two questions at this point:
1. Can we control when commits happen? The goal is to commit offsets at the end of the sequence, not for each item. Should we make a change to the core for that?
1. How can we have a more specific subscriptions? If I want to route according to other criterias than the type (e.g. the topic or some header) how can I do that?

**Comment by BEagle1984** [comment] 2020-08-27 16:30
Mmmh...I see it a bit differently at the moment but I really need to think thoroughly about it.

> 1. A new module `Silverback.Integration.Sequence` providing dataset and streamed chunking. The goal is to have a minimum impact to the rest of the codebase.

I don't think that's a good idea. Batches and chunking are already supported in Silverback.Integration and they need to be extended with (or replaced by) the new features.

> 2. Providing a message type `Sequence<T>`

I do like the `Sequence<TMessage>` idea. 👍 

> 3. Support enabled with something like `.AddSequenceSupport<T>()` to the configuration.

I don't know. Right now the configuration is made per inbound/outbound connector and I think it should remain in there. It is more related to the topic being produced to or consumed from, than the message type. I fear it would create some weird edge cases if we configure at message type level but we either have the same message type used in different topics or multiple message types in the same topic.

I do think the configuration should still be in the `IEndpoint` (/`IProducerEndpoint `/`IConsumerEndpoint`). Like the serialization settings and of course the current `ChunkSettings` (the `BatchSettings` are also to be moved into the endpoint in v3.0).

> 4. This creates a new subscriber for T, a `SequenceItemSubscriber<T>`
> 5. Upon receiving the first item of a sequence, it will publish a sequence message backed with a `BlockingCollection` of size 1 and will write the sequence items into this blocking collection. The sequence message is of type `Sequence<T>` which contains the sequence id and an `IEnumerable<T>`
> 6. Consumers can subscribe to `Sequence<T>` as they would subscribe to other message types.
> 7. When T is byte[], then an additional internal subscriber is created. It listens to `Sequence<byte[]>` and publishes `BinarySequence` which contains the sequence id and a `Stream` backed by the blocking collection.

I do like the `Sequence<TMessage>` idea and leveraging the `BlockingCollection` to handle the back pressure.
I think it should be handled with the broker behaviors though, like the rest of the features (and the current chunking/batching implementation).
 
> I have two questions at this point:
> 
> 1. Can we control when commits happen? The goal is to commit offsets at the end of the sequence, not for each item. Should we make a change to the core for that?

In the `IConsumerBehavior` you can already control it. I've to admit that it isn't the piece of code I'm most proud of, as the implementation is not the cleanest ever, but it does it's job.
See https://github.com/BEagle1984/silverback/blob/master/src/Silverback.Integration/Messaging/LargeMessages/ChunkAggregatorConsumerBehavior.cs#L71.

> 2. How can we have a more specific subscriptions? If I want to route according to other criterias than the type (e.g. the topic or some header) how can I do that?

If you mean in the internal bus you got basically two options:
* Subscribe to the `IInboundEnvelope<TMessage>` (that contains all the headers and endpoint details, as well as the message) and manually discard the messages (`if (envelope....!= whatever) return;`.
* Create your custom `MessageFilterAttribute`. This is not a documented featured but it is what I used to implement the [`KafkaGroupIdFilterAttribute`]( https://github.com/BEagle1984/silverback/blob/master/src/Silverback.Integration.Kafka/Messaging/Subscribers/KafkaGroupIdFilterAttribute.cs).

I don't think so but if you maybe mean how to route the outbound messages: https://beagle1984.github.io/silverback/docs/configuration/outbound#dynamic-custom-routing

**Comment by BEagle1984** [comment] 2020-08-27 16:37
@lbovet take all this with a grain of salt please. I need some time to look into the code and maybe mess around with a prototype to figure out how all this combines with the existing features.

**Comment by BEagle1984** [comment] 2020-08-28 07:28
Amazing, I just noticed that yesterday I had replied to the message here below, but I forgot to actually post it. Here it is.

> Yes, consuming is the tricky part. In any case, the existing support for chunking is not really helpful for a streaming solution.
> 
> For consuming, the challenge is to transform the flow of messages pushed by the poll loop into a flow of pulled messages (IEnumerable in the general case, Stream in the binary chunk case).
> 
> And we need back pressure if we don't read the Stream as fast as the messages are produced. If everything runs sync, we just introduce a blocking queue in the middle. I have not yet understood the threading model between the Kafka Consumer and the "internal bus". What happens if my business consumer blocks the thread in OnMessage(...)? Does it also block the poll loop of the consumer? Is it problem?

Yes, at the moment it is just all synchronous. The poll loop is blocked until all subscribers have processed the message.
I don't think it is currently a problem but you gotta be careful with the max poll interval settings.
I thought a lot about this but I decided for the simplest flow possible: poll -> invoke subscribers -> commit (if no exception) -> poll  to consume next message. For chunked messages it is actually a bit different: poll -> store chunk -> poll -> store chunk -> ... -> poll -> aggregate message -> invoke subscribers -> commit -> poll again (and similar for the batch of messages being processed as an IEnumerable).
Of course this has to change to properly support streaming and the subscribers have to be called from a separate thread, without blocking the poll loop.

🤔 

Interesting!
I will have a look at it and maybe try to build up a prototype.

**Comment by BEagle1984** [comment] 2020-08-28 07:28
Some extra thoughts...

One thing that may be tricky is to properly handle polymorphism, since Silverback is meant to allow messages of different types being trasferred through the same topic and it fully supports polymorphism in the subscribers. It means that you could fpor example subscribe to an `IEnumerable<TMessage>` , where `TMessage` is a specific type and Silverback filters the incoming messages batch and forwards to the method only the messages that are assignable to the type `TMessage`.
Another thing is that the enumerables tend to be materialized as soon as possible, to prevent multiple enumerations. Of course this has to change and we gotta be careful with that.

**Comment by lbovet** [comment] 2020-08-28 08:16
1) Okay, the discussion about having it implemented in Silverback.Integration or another module is interesting. If we do so, I expect that the existing "in memory chunk aggregation" would be actually re-implemented using the underlying "streamed chunking" stuff that we are defining now. This would be one of the pros. My proposal to have it outside had the idea to make the boundary clear and avoid cluttering the existing stuff (an approach I often have with contributions). It's basically aour choice to consider sequences and chunking a "core feature", and thus have them in the Integration module. 
1b) I wonder if all this raises the question of the current chunking suppotr. Is it actually useful to provide the pluggable chunkstore if the whole things is at the end be kept in memory? Don't you think that this chunking support will probably be changed and actually a breaking change?
3) Right, it is very ok to have the sequence at the connector/endpoint level.
4) I'll have a look how we can replace my proposal of "internal subscribers" with behaviors.

Q1) Good, we can manipulate the offsets to commit in the context. That's a good point. It is actually an argument to use behaviors since they have access to the context (and not the subscribers, right?).
Q2) This is a nice secret feature!

**Comment by BEagle1984** [comment] 2020-08-28 09:19
> 1. Okay, the discussion about having it implemented in Silverback.Integration or another module is interesting. If we do so, I expect that the existing "in memory chunk aggregation" would be actually re-implemented using the underlying "streamed chunking" stuff that we are defining now. This would be one of the pros. My proposal to have it outside had the idea to make the boundary clear and avoid cluttering the existing stuff (an approach I often have with contributions). It's basically aour choice to consider sequences and chunking a "core feature", and thus have them in the Integration module.

Yes, the existing chunking feature has to be rewritten, based on the new one. It basically all boils down to buffering until the entire message is aggregated.

Anyhow, I decided to cut the modules (nuget packages) according to the dependencies more than anything else. Since this stuff doesn't depend on anything I'd keep it into Silverback.Integration. For simplicity, to avoid the users being confused by a ton of packages. Right now you basically just need to reference Silverback.Integration.Kafka and you get all the features you normally need (since it references Silverback.Integration that in turns references Silverback.Core), unless you use Avro.

>    1b) I wonder if all this raises the question of the current chunking suppotr. Is it actually useful to provide the pluggable chunkstore if the whole things is at the end be kept in memory? Don't you think that this chunking support will probably be changed and actually a breaking change?

I've no problem with introducing a breaking change at this point, where I'm just a bout to release a major version. So the timing would be just perfect.

That being said the chunk store is meant to allow for another temporary storage (DB, S3, whatever). I guess that if you deal with very big files or if the chunks are for whatever reason spread across multiple partitions, then the intermediate storage gives you a better flexibility, even though it's imo not a best practice.

> 2. Right, it is very ok to have the sequence at the connector/endpoint level.
> 3. I'll have a look how we can replace my proposal of "internal subscribers" with behaviors.

👍 

> Q1) Good, we can manipulate the offsets to commit in the context. That's a good point. It is actually an argument to use behaviors since they have access to the context (and not the subscribers, right?).

Yes, right. For simplicity the message broker details are hidden to the subscribers.

> Q2) This is a nice secret feature!

😆

**Comment by lbovet** [comment] 2020-08-28 09:37
About the chunk store and the current chunking implementation, you can deal with very big files and store your chunks in the S3 chunkstore while you receive them. But once you have received all chunks, you rebuild the whole message in memory to send it to the internal bus. That means that you allocate everything.
Maybe the chunkstore configuration should have a way to choose if the actual message has to be rebuilt or if another type must be sent (e.g. the URL of the S3 bucket), let to the implementation of the chunkstore.
This can be a convergence with the Sequence<TMessage> or BinarySequence concept since are all just "views" on the whole sequence like the URL is. We have individual message as input, a behavior transforming it in the middle, and the "sequence view" as output.

**Comment by BEagle1984** [comment] 2020-08-28 17:40
> About the chunk store and the current chunking implementation, you can deal with very big files and store your chunks in the S3 chunkstore while you receive them. But once you have received all chunks, you rebuild the whole message in memory to send it to the internal bus. That means that you allocate everything.

Yes, I should give it back as stream. But the intermediate store gives you the chance to not restart from the beginning if you restart your client app. Maybe I'm just overthinking it.

The intermediate store also allows to handle the case where all the chunks aren't in the same partition, are interleaved with other messages or a rebalance occurs. But sure, this is also something we need to rethink now.

> Maybe the chunkstore configuration should have a way to choose if the actual message has to be rebuilt or if another type must be sent (e.g. the URL of the S3 bucket), let to the implementation of the chunkstore.
> This can be a convergence with the Sequence or BinarySequence concept since are all just "views" on the whole sequence like the URL is. We have individual message as input, a behavior transforming it in the middle, and the "sequence view" as output.

This is maybe a step too much for this library. I mean, Silverback will provide the stream, while the client can store it wherever he wants (file system, s3, blob storage, db, ...).

**Comment by BEagle1984** [comment] 2020-08-28 18:09
A quick update, I thought a bit about the possible design and there are some first random thoughts and rough ideas:
1. The consumer (pipeline) should now return an enumerable (`MessageEnumerable`) that will pull from an internal `BlockingCollection` (to handle the back pressure).
1. The consumer (pipeline) appends the next messages to the same `MessageEnumerable`.
1. Some behaviors will be added to the pipeline to handle the sequencing. That simply means to create and publish a new `MessageEnumerable` and/or end the previous one(s). Yes, I'd consider the possibility to allow multiple ones to be active at the same time (e.g. for the case where you have multiple producers and the chunks may be interleaved). An abstract `SequenceConsumerBehavior` will probably provide some basic structure and make it easier to implement new types of sequence.
1. Rx should automatically be supported by the current Silverback.Reactive package, since all I do is transforming the `IEnumerable` into an `IObservable`.
1. The `BinaryChunksSequenceConsumerBehavior` will be a special behavior that is used for binaries and returns a `BinaryFileStreamMessage` exposing the binary stream as well as the file metadata information (or maybe I'll just replace the byte array in the current `BinaryFileMessage`). This behavior is active only when the `BinaryFileMessageSerializer` kicks in (either because explicitly configured or because the message type header indicates a binary file, the latter is probably only relevant for Silverback-to-Silverback communication)
1. On producer side I'll have some `SequenceProducerBehavior` implementations for chunking (split into chunks and add headers) and other types of sequences.
1. The master data use case will be handled with a `MessageSet<TMessage>` that the producer pipeline (actually the `MessageSetSequenceProducerBehavior`) will take care of decorating each contained message with the necessary headers.
1. The mediator (`Publisher`) has to be refactored to avoid materializing the enumerable, unless the subscriber signature wants a materialized collection (e.g. `IReadOnlyCollection` vs. `IEnumerable`).
1. The current batching (based on count and timeout) will be redesigned to use the same approach with a `BatchSequenceConsumerBehavior`.
1. Some events will be published when a new `MessageEnumerable` is created and completed to allow the client to subscribe to the single message and handle the operation setup and commit separately. To maintain some compatibility with today's batch (https://beagle1984.github.io/silverback/docs/configuration/inbound#batch-processing)

Well, more or less this...all to be validated, of course.

**Comment by BEagle1984** [comment] 2020-08-28 18:15
Note that with this approach, the `IEnumerable` (or `IObservable`) being subscribed will get the full messages stream, unless there is a `SequenceConsumerBehavior` kicking in to break it in segments.
I think this may be a very neat implementation indeed.

**Comment by lbovet** [comment] 2020-08-30 06:28
Your proposed design ideas look very good to me.
I am going to look into the codebase to see what I could do.  I guess you will start with the mediator changes and the changes needed to introduce the sequences as a "first-class citizen". I'll maybe have a look at BinaryChunksSequenceConsumerBehavior. The thing converting a Sequence<byte[]> into a Stream. It is quite isolated...

**Comment by BEagle1984** [comment] 2020-08-30 07:57
Yep, I actually started already with a prototype. What I figured out so far is that it will require quite a bit of refactoring to be able to keep all features, handle the commits correctly, etc.

What I currently began with:
* `RawInboundEnvelopeEnumerable`, that is an implementation of `IEnumerable<IRawInboundEnvelope>` that intermediately stores the messages in a `BlockingCollection`. It basically exposes an `Add` method, used by the consumer, and a `Complete` method, to signal the end of the sequence. This is what I originally called `MessageEnumerable`, but I think this name is more accurate.
* `StreamConsumerBehavior`, that will be probably be the last behavior in the consumer pipeline, taking care of creating the `RawInboundEnvelopeEnumerable` for the first message, appending all other messages to it (via `Add`) and take care ot the offset commit as soon as the current message has been successfully consumed from the enumerable. (This is one thing I immedialtely figured out, the commit thing will work a bit differently since the message processing will now potentially happen in a separate thread).
* `PublisherConsumerBehavior`, that will publish the enumerable to the internal bus. This task is currently accomplished by the `InboundConnector` but I think it's now time to get rid of the connectors completely and move all logic into the behaviors (cleaner, more flexible and straightforward when dealing with commits and so on).

What I'm working on is basically the endless stream case. In a second step the `StreamConsumerBehavior` has to be refactored to either extract the base `SequenceConsumerBehavior` (and create other behaviors to be prepended to the `StreamConsumerBehavior` to split the sequences where needed) or use a sort of `ISequencer` (maybe with a nicer name) that is configured in the `IConsumerEndpoint` and whose sole purpose is to identify the start/end of a sequence and which message belongs to it, in order to add the messages to the right `RawInboundEnvelopeEnumerable`. The latter sounds more natural to me.
If we go down the sequencer route, for the binary file chunking case we will have a `ChunksSequencer` to read the headers and create the enumerables accordingly, plus another behavior (placed after the `StreamConsumerBehavior`) that transforms each `RawInboundEnvelopeEnumerable` into the `BinaryFileStreamMessage`.

We probably need to create an implementation of `System.IO.Stream` for our purpose and use it in the `BinaryFileStreamMessage.Stream` property. This would be a good starting point for you. 👍 

⚠️ There is one thing I still haven't fully figured out: how to properly (and cleanly) handle the chunked JSON message. In that case you really want it to be aggregated back in memory and deserialized before it is published to the internal bus. The issue is that the aggregated message has to be deserialized and only afterwards pushed to the `RawInboundEnvelopeEnumerable`, so the aggregator should be at the beginning of the pipeline, but if the sequencer is the last part of the pipeline it cannot work... I have some ideas but they need to be verified.

(PS: Have a nice and nerdy Sunday my friend 🤓)

**Comment by lbovet** [comment] 2020-08-30 08:28
Great! I think your plan makes sense. I am actually on the stream implementation.
Share a branch as soon as possible, so that I can use RawInboundEnvelopeEnumerable. I don't care if it is not stable, I'll rebase all the way.

**Comment by BEagle1984** [comment] 2020-08-30 08:35
Yes, sure, I'll push as soon as it at least compiles again. In the meanwhile here is the draft version I wrote so far: https://gist.github.com/BEagle1984/bf57e22a2c0de454c61aa5b833ba3d6f.
⚠️ Beware, I didn't test it.

(Heading to the gym now, will be back later for a full immersion)

**Comment by lbovet** [comment] 2020-08-30 15:18
Had not so much time I expected today... Did that nevertheless: https://github.com/BEagle1984/silverback/compare/master...lbovet:chunk-stream?expand=1

Indeed, code style support in VSCode is not sufficient. I will continue with VS full in the office.

**Comment by lbovet** [comment] 2020-08-31 13:13
I want to base my branch on feature/streaming. Could you avoid force-pushes so that I don't have surprises when rebasing?
We can always squash the branch afterward.

**Comment by BEagle1984** [comment] 2020-08-31 13:54
> I want to base my branch on feature/streaming. Could you avoid force-pushes so that I don't have surprises when rebasing?
> We can always squash the branch afterward.

I force pushed because I rebased my branch on master. 😆 

I'll try to minimize it anyway. Nice to know so I will in case create another branch for me, to transfer unfinished/uncompiling code for example, since I work on multiple notebooks.

**Comment by lbovet** [comment] 2020-09-07 08:36
Should we take the opportunity to align the header names with "emerging standards?".
| Header | Description |
|---------|--------------|
| **x-chunk-index**  | The chunk number, starting at zero. |
| **x-chunk-count** | The total number of chunks if known. |
| **x-chunk-last** | Boolean marking the last chunk (mandatory if x-chunk-count is not used). |
| **x-chunk-first-offset** | Offset of the first chunk. Present in all chunks except the first one itself. |

**Comment by BEagle1984** [comment] 2020-09-07 08:40
Sure, I don't have a strong opinion about the "correct" header names. We can set whatever we want as default, they can be customized in the app startup anyway.
But are those really a standard? Or are they made up?

**Comment by lbovet** [comment] 2020-09-07 09:12
They are standards in some big company that is an active user and contributor of Silverback!

**Comment by BEagle1984** [comment] 2020-09-12 14:13
@lbovet I merged the `ChunkStream`. (Thank you!)
But now I wonder if we shouldn't have explicitly  implemented the `ReadAsync` method as well. In your implementation you are always gonna block (`Enumerator.MoveNext` is blocking until the next chunk is consumed, while `AsyncEnumerator.MoveNextAsync` would free the thread).

**Comment by lbovet** [comment] 2020-09-12 18:36
Yes, I also though about it. In fact, supporting a Stream is interesting when we use other libraries (CSV/XML parsers for example) to process the binary data. I assumed that most of these libraries would use the blocking methods of Stream, but I don't know enough of the .NET ecosystem and maybe they are all modern enough to be fully non-blocking. I guess that we should support the blocking case anyway. That forces us to call the Stream consumer in a dedicated thread (from an elastic thread pool).

**Comment by lbovet** [comment] 2020-10-27 08:05
Are the headers already as specified in https://github.com/BEagle1984/silverback/issues/106#issuecomment-688164572 ?

**Comment by BEagle1984** [comment] 2020-10-27 08:22
Yes, they are: https://github.com/BEagle1984/silverback/blob/3aa777a1e492cb1504b51c725eadfd2e51532b24/src/Silverback.Integration/Messaging/Messages/DefaultMessageHeaders.cs#L40.

(It works with "your" producer out of the box, without any customization.)

**Comment by BEagle1984** [comment] 2020-11-12 10:08
A few beta versions including this feature have been released. The current latest version is [v3.0.0-beta.streaming.5](https://github.com/BEagle1984/silverback/releases/tag/v3.0.0-beta.streaming.5) and is currently being tested (both by me and in a project).

**Comment by BEagle1984** [comment] 2021-03-14 17:53
Silverback v3.0.0 has been released, including this feature.

**Closed by BEagle1984** 2021-03-14 17:53 UTC
Labels: enhancement
